# This file was generated by GoReleaser. DO NOT EDIT.
class AwsAuth < Formula
  desc "CLI for authenticating against AWS"
  homepage "https://github.com/telia-oss/aws-auth"
  version "0.0.1"

  if OS.mac?
    url "https://github.com/telia-oss/aws-auth/releases/download/v0.0.1/aws-auth-0.0.1-darwin-amd64.tar.gz"
    sha256 "c3cd489d5724f72ab3b12705da813233f2dc834772426f703945d8a718433a42"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/telia-oss/aws-auth/releases/download/v0.0.1/aws-auth-0.0.1-linux-amd64.tar.gz"
      sha256 "00a606d1c4268cc73eec53e0b874d454d905bf067953374ef2ad3d57eb1e4a3d"
    end
  end

  def install
    bin.install "aws-auth"
  end

  test do
    system "#{bin}/aws-auth --version"
  end
end
