# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsEnv < Formula
  desc "A small binary for securely handling secrets in environment variables on AWS."
  homepage "https://github.com/telia-oss/aws-env"
  version "1.1.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/telia-oss/aws-env/releases/download/v1.1.0/aws-env-1.1.0-darwin-amd64.tar.gz"
    sha256 "14aef0fb72a9bdad8be8c5f37081c78943f9ffa8b1e76ffbb2491baa24bdec33"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/telia-oss/aws-env/releases/download/v1.1.0/aws-env-1.1.0-linux-amd64.tar.gz"
    sha256 "c4147fb38fdbfb276b398668591269de6f6a343deec699f8991eb9b52d850ef6"
  end

  def install
    bin.install "aws-env"
  end

  test do
    system "#{bin}/aws-env --version"
  end
end
