# This file was generated by GoReleaser. DO NOT EDIT.
class CloudConnect < Formula
  desc "CLI for managing transit gateway attachments."
  homepage "https://github.com/telia-oss/cloudconnect"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/telia-oss/cloudconnect/releases/download/v0.0.2/cloud-connect-0.0.2-darwin-amd64.tar.gz"
    sha256 "a3b5c469b201daa0d4e173cdccfc8b84b2609c86147a8b6a22b6682af3f397ba"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/telia-oss/cloudconnect/releases/download/v0.0.2/cloud-connect-0.0.2-linux-amd64.tar.gz"
      sha256 "1677e3fe3dd0d9c6baacf690d1431632326941dccc59f7a195b577fe63315e73"
    end
  end

  def install
    bin.install "cloud-connect"
    bin.install "autoapprover"
  end

  test do
    system "#{bin}/cloud-connect --version"
  end
end
